# Generated by Django 4.0.2 on 2022-02-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_case_updatedon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='updatedon',
        ),
    ]
